name = "backend"
compatibility_date = "2024-07-20"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTI5ZDFlZWUtZjgwYS00M2EzLThjMmItZmJlNzMxMjllNjBiIiwidGVuYW50X2lkIjoiOGMxY2U2MDA1ZWZiODE1YTQxMTIzNzk4ZDRiNmI2YTIwZGY0N2Q4MmYxOTVkNzJhN2UxOWJhNTQxMWU0ZTNmZiIsImludGVybmFsX3NlY3JldCI6ImEyYTE1ZWVmLTgyODktNGU2Ni1hOWNiLTYzMDdjMjJhNDk5YyJ9.EHMbY2wFTZUhmoYl5WTkJUUvGHV2-o8dFTcyziy_oTU"
JWT_SECRET= "SECRET"

